### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-jquery-ajax#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://familiar-hose.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/jquery-ajax/1) criteria:
- [x] One of the following APIs is used to list information on your website with jQuery Ajax:
  - [Star Wars API](https://swapi.co/) (extra points if results are displayed in Wookiee)
  - [Pokémon API](http://pokeapi.co/)
  - [Cheapshark API](http://www.cheapshark.com/api/) (for videogame deals)
  - [USDA Farmers Markets API](http://search.ams.usda.gov/farmersmarkets/v1/data.svc/zipSearch?zip=48823)
  - [JSON Placeholder API](http://jsonplaceholder.typicode.com/) (has a lot of fake, example data)
- [x] Data from the API is formatted into HTML that makes it easy to read.

**Comment by chrisvfritz** [comment]
I'm getting an error on the hosted site:

```
Uncaught TypeError: response.map is not a function                             (index):20
```

**Comment by chrisvfritz** [comment]
@KatieMFritz Just pinging on this, as one of the new dashboards let me know it was still pending. 😃

**Comment by chrisvfritz** [comment]
@KatieMFritz Ping. 😸

**Comment by chrisvfritz** [comment]
Ping ping. 😄

**Comment by KatieMFritz** [comment]
I think this is fixed now!

**Comment by chrisvfritz** [comment]
:shipit: 🎉
